/**
 * DEV-ONLY TEST WORD LISTS FOR MID-ROUND TEST MODE (Milestone 4.5)
 *
 * WARNING: DO NOT USE THESE IN PRODUCTION ROUND SELECTION.
 * These word lists are specifically for development testing only.
 *
 * Used by lib/devMidRound.ts to populate test rounds with realistic data.
 */

/**
 * Test Answer Words - Pool for selecting dev test round answers
 * ~100+ words for variety in testing
 */
export const TEST_ANSWER_WORDS: string[] = [
  "MUSIC","NAVAL","RADIO","GRACE","IVORY","LEMUR","MOCHA","NOTCH","QUALM",
  "PENAL","HAZEL","HALVE","KNEAD","TONIC","PIXEL","FABLE","BLADE","ANGEL",
  "CLEAN","STORM","PRISM","MAGIC","NINJA","OCEAN","TOWER","VIRAL","APPLE",
  "CRANE","GHOST","HONEY","NORTH","QUIET","ROAST","SHAPE","TANGO","VALID",
  "WORTH","YEARN","ZONED","AMBER","BERRY","CHESS","DITCH","ELBOW","FROST",
  "GROVE","HABIT","IDLER","JAZZY","KINKY","LIVER","ORBIT","PETAL","QUAKE",
  "RHYME","SOLID","THEME","UPPER","WOVEN","YOUTH","BASIC","DOUBT","EQUIP",
  "FANCY","GIANT","HEART","IDEAL","JOKER","KOALA","LEVEL","MIGHT","NOVEL",
  "ONION","RAPID","UNION","WRIST","YODEL","CHIRP","DREAM","ELITE","FLAKE",
  "GRIND","HEDGE","ICING","JELLY","KNELL","LASER","MIRTH","NERVE","OPINE",
  "QUOTA","RIVER","SCARF","TIDAL","ULTRA","VERGE","WHALE","YUMMY","ZESTY",
  "AMUSE","BLEND","CLERK","DROOP","ENACT","FIBER","GLOAT","JUMBO","KARMA",
  "LOFTY","MOTOR","NUTTY","OMEGA","PRIDE","QUARK","ROBIN","SMIRK","TRAIL",
  "USAGE","VIXEN","WHEAT","YOUNG","ZAPPY"
];

/**
 * Test Seed Words - For populating cosmetic wheel seeds in dev test rounds
 * ~80+ words, NO OVERLAP with TEST_ANSWER_WORDS
 */
export const TEST_SEED_WORDS: string[] = [
  "ABACK","BISON","CLOUD","DELTA","EPOCH","FOCAL","GAUNT","HAVEN","INLET",
  "JOLLY","MANGO","NOBLE","OPINE","PATIO","QUART","SAUCY","TANGY","ULCER",
  "VIVID","WIDEN","YACHT","ZEBRA","ACORN","BLINK","CHAMP","DROVE","EJECT",
  "FLOUR","HOVER","ILIAC","JUNTO","LANKY","MELON","NINTH","OTTER","PINCH",
  "QUASI","RUPEE","SHARD","TOPAZ","UNCLE","VAPID","WOOZY","YIELD","ZONER",
  "APART","BANJO","CUMIN","DROSS","ETHER","FLUID","GAUZE","HUMPH","IODIC",
  "JOIST","LADEN","MERIT","NAVEL","OCTAL","PALER","QUOTH","RIGID","SABLE",
  "TWEAK","UPTOR","VALET","WISPY","ABASE","BURLY","CEDAR","DONUT","ELFIN",
  "FJORD","GUILT","HUTCH","IVIED","LIGER","MACHE","NOMAD","OPERA","PSALM",
  "QUICK","REEDY","SKATE","TOXIC","UNFED","VROOM","WEEDY","ADOBE","BRINE",
  "CRISP","DECOY","EXPEL","FLINT","GNOME","HINGE","IGLOO","JERKY","KIOSK",
  "LLAMA","NUDGE","OZONE","PLUMB","RIDGE","SPICE","TAUNT","UMBRA","VIPER",
  "WHISK","XYLEM","YUCCA","ALIBI","BROTH","CLOWN","DEBUT","EMBED","FUDGE",
  "GAVEL","IDYLL","JOUST","KUDOS","LEECH","MULCH"
];

/**
 * Test Guess Words - Large pool for simulating many wrong guesses
 * Includes TEST_ANSWER_WORDS + TEST_SEED_WORDS + hundreds more valid 5-letter words
 */
export const TEST_GUESS_WORDS: string[] = [
  ...TEST_ANSWER_WORDS,
  ...TEST_SEED_WORDS,

  // Additional ~400+ words to create a realistic "busy wheel" experience
  "ABOUT","ABOVE","ACUTE","ADMIT","ADORE","ADULT","AFIRE","AGENT","AGLOW","AGREE",
  "AHEAD","AIDER","AISLE","ALGAE","ALIVE","ALLOW","ALOUD","ALPHA","ALTAR","AMEND",
  "AMISS","AMONG","AMPLE","ANGRY","ANKLE","ANNOY","ANTIC","ANVIL","APRON","ARDOR",
  "ARISE","ARMOR","AROMA","ARROW","ASCOT","ASIDE","ASKED","ASPEN","AVAIL","AVERT",
  "AVIAN","AVOID","AWAIT","AWARD","AWARE","AWASH","AWFUL","AWOKE","AXIAL","AXIOM",
  "BADGE","BALER","BALMY","BALSA","BANAL","BARGE","BASIL","BATCH","BATON","BAYOU",
  "BEACH","BEADY","BEAST","BELCH","BELIE","BIRTH","BLEED","BLIND","BLISS","BLITZ",
  "BLOAT","BLOCK","BLOOD","BLUNT","BLURB","BLURT","BOARD","BOAST","BOBBY","BOGUS",
  "BOOTH","BOOST","BORAX","BOTCH","BOUGH","BOUND","BOWEL","BOXER","BRAIN","BRAKE",
  "BRAND","BRASS","BRAVE","BRAVO","BRAWL","BRAWN","BREAK","BREED","BRIAR","BRIBE",
  "BRIEF","BRINK","BROAD","BROIL","BROKE","BRONC","BROOD","BROOM","BROWN","BRUNT",
  "BRUSH","BRUTE","BUDGE","BUGGY","BUILD","BUILT","BULKY","BULLY","BUNCH","BUNNY",
  "BURNT","BURST","BUXOM","CABIN","CABLE","CACAO","CACHE","CACTI","CADDY","CADET",
  "CAGEY","CAIRN","CAMEL","CAMEO","CAMPS","CANAL","CANDY","CANOE","CANON","CAPER",
  "CAPUT","CARAT","CARBO","CARDS","CAROL","CARRY","CARTS","CARVE","CASTE","CATCH",
  "CATER","CAVIL","CEASE","CELLO","CHAFE","CHAIR","CHANT","CHAOS","CHAPS","CHART",
  "CHASE","CHEAP","CHEER","CHEST","CHIME","CHINA","CHOKE","CHORD","CHORE","CHOSE",
  "CHUCK","CHUMP","CHUNK","CHURN","CIGAR","CINCH","CIVIC","CLACK","CLAIM","CLAMP",
  "CLANG","CLANK","CLASH","CLASP","CLASS","CLAUS","CLEAR","CLEAT","CLEFS","CLICK",
  "CLIFF","CLIMB","CLING","CLINK","CLINT","CLONE","CLOTH","CLOVE","CLUMP","CLUNG",
  "COACH","COAST","COBRA","COCOA","CODER","COILS","COINS","COLON","COLOR","COMET",
  "COMFY","COMIC","COMMA","CONCH","CONDO","CONIC","COPSE","CORAL","CORER","CORNY",
  "COUCH","COUGH","COULD","COUNT","COURT","COVER","COVET","COWER","CRACK","CRAFT",
  "CRANK","CRATE","CRAVE","CREDO","CREED","CREEK","CREEP","CREPT","CRIME","CRIMP",
  "CROAK","CROCK","CRONE","CRONY","CROOK","CROSS","CROUP","CROWD","CROWN","CRUDE",
  "CRUEL","CRUMB","CRUSH","CRUST","CRYPT","CURRY","CURSE","CURVE","CYCLE","CYNIC",
  "DADDY","DAILY","DAIRY","DANCE","DANDY","DARTS","DASHY","DATED","DATUM","DAZED",
  "DEALT","DEATH","DEBAR","DEBIT","DEBUG","DECAL","DECAY","DECOR","DECRY","DEDIC",
  "DEFER","DEIGN","DELAY","DELVE","DEMON","DEMUR","DENIM","DENSE","DEPOT","DEPTH",
  "DERBY","DEUCE","DEVIL","DIARY","DICEY","DIGIT","DILLY","DIODE","DIRGE","DIRTY",
  "DISCO","DITTY","DIVER","DIVOT","DIZZY","DODGY","DOGMA","DOING","DOLLY","DONOR",
  "DOPEY","DORSI","DOTTY","DOWDY","DOWEL","DOWER","DOWNY","DOWRY","DOZEN","DRAFT",
  "DRAMA","DRAPE","DRAWL","DRAWN","DREAD","DREGS","DRESS","DRIED","DRIER","DRIFT",
  "DRILL","DRINK","DRIVE","DROIT","DROLL","DRONE","DROPS","DROWN","DRUID","DRYLY",
  "DUCAT","DUCHY","DUMMY","DUMPS","DUMPY","DUNCE","DUSKY","DUSTY","DUTCH","DUVET",
  "DWARF","DWELL","DWELT","DYING","EAGER","EAGLE","EARLY","EARTH","EASEL","EATEN",
  "EATER","EBONY","ECLAT","EDGED","EDICT","EERIE","EIGHT","EJECT","EKING","ELAND",
  "ELATE","ELDER","ELECT","ELEGY","ELFIN","ELIDE","ELITE","ELOPE","ELUDE","ELVES",
  "EMAIL","EMBER","EMCEE","EMERY","EMOJI","EMPTY","ENACT","ENDED","ENDOW","ENEMY",
  "ENJOY","ENNUI","ENTER","ENTRY","ENVOY","EQUAL","ERASE","ERECT","ERROR","ERUPT",
  "ESSAY","ESTER","ESTOP","ETHER","ETHIC","ETHOS","EVADE","EVENT","EVERY","EVICT",
  "EVOKE","EXACT","EXALT","EXCEL","EXERT","EXILE","EXIST","EXPAT","EXTOL","EXTRA",
  "EXUDE","EXULT","FACET","FAINT","FAIRY","FAITH","FALSE","FAMED","FATAL","FATSO",
  "FATTY","FAULT","FAUNA","FAVOR","FEAST","FEIGN","FEINT","FELON","FEMUR","FENCE",
  "FERAL","FERRY","FETCH","FEUD","FEVER","FEWER","FIBER","FIELD","FIEND","FIERY",
  "FIFTY","FIGHT","FILCH","FILET","FILLY","FILTH","FINAL","FINCH","FINER","FIRST",
  "FISHY","FIXER","FJORD","FLACK","FLAIL","FLAIR","FLAME","FLANK","FLARE","FLASH",
  "FLASK","FLECK","FLEET","FLESH","FLICK","FLIER","FLING","FLINT","FLIRT","FLOAT",
  "FLOCK","FLOOD","FLOOR","FLORA","FLOSS","FLOUR","FLOUT","FLOWN","FLUFF","FLUID",
  "FLUKE","FLUNG","FLUNK","FLUSH","FLUTE","FOAMY","FOCAL","FOCUS","FOGGY","FOIST",
  "FOLLY","FORAY","FORCE","FORGE","FORGO","FORTE","FORTH","FORTY","FORUM","FOUND",
  "FOYER","FRAIL","FRAME","FRANK","FRAUD","FREAK","FREED","FRESH","FRIAR","FRIED",
  "FRILL","FRISK","FRITZ","FROCK","FROGS","FROND","FRONT","FROST","FROTH","FROWN",
  "FROZE","FRUIT","FRUMP","FUDGE","FUGUE","FULLY","FUMED","FUNGI","FUNKY","FUNNY",
  "FURRY","FUSED","FUSSY","FUZZY","GAILY","GAMER","GAMMA","GAMUT","GASSY","GAUDY",
  "GAVEL","GAWKY","GAZER","GECKO","GEESE","GENIE","GENRE","GHOUL","GIANT","GIDDY",
  "GIFTS","GIRLS","GIRTH","GIVEN","GIVER","GIZMO","GLADE","GLAND","GLARE","GLASS",
  "GLAZE","GLEAM","GLEAN","GLIDE","GLINT","GLOAT","GLOBE","GLOOM","GLORY","GLOSS",
  "GLOVE","GNASH","GNOME","GOING","GOLEM","GONER","GOODY","GOOEY","GOOFY","GOOSE",
  "GORGE","GOUGE","GOURD","GRACE","GRADE","GRAFT","GRAIN","GRAND","GRANT","GRAPE",
  "GRAPH","GRASP","GRASS","GRATE","GRAVE","GRAVY","GRAZE","GREAT","GREED","GREEK",
  "GREEN","GREET","GRIEF","GRILL","GRIME","GRIMY","GRIND","GRIPE","GROAN","GROIN",
  "GROOM","GROPE","GROSS","GROUP","GROUT","GROVE","GROWL","GROWN","GRUEL","GRUFF",
  "GRUNT","GUARD","GUAVA","GUESS","GUEST","GUIDE","GUILD","GUILE","GUILT","GUISE",
  "GULCH","GULLY","GUMMY","GUSTY"
];
